# Generated by Django 4.1.2 on 2022-11-03 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTematica',
            fields=[
                ('AreaID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('DataCriacao', models.DateField()),
                ('CodigoValidacao', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('CursoID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
                ('CargaHoraria', models.IntegerField()),
                ('DataCriacao', models.DateField()),
                ('Aprovado', models.BooleanField(default=None, null=True)),
                ('AreaTematica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.areatematica')),
            ],
        ),
        migrations.CreateModel(
            name='Titulacao',
            fields=[
                ('TitulacaoID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TopicoDeAula',
            fields=[
                ('TopicoID', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=120)),
                ('Descricao', models.CharField(max_length=500)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ProfessorID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
                ('DataNascimento', models.DateField()),
                ('CPF', models.CharField(max_length=20, unique=True)),
                ('Senha', models.CharField(max_length=50)),
                ('Titulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.titulacao')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='ProfessorResponsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.professor'),
        ),
    ]
