# Generated by Django 4.1.2 on 2022-11-03 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='Usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
