# Generated by Django 4.1.2 on 2022-11-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0004_alter_professor_datanascimento_alter_professor_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='CPF',
            field=models.CharField(max_length=20),
        ),
    ]
