# Generated by Django 4.1.2 on 2022-11-03 23:08

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0005_alter_professor_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='CPF',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
    ]
